name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Xcode version
        run: xcodebuild -version

      - name: Test
        run: |
          xcodebuild \
            -project Powerflow.xcodeproj \
            -scheme Powerflow \
            -destination "platform=macOS" \
            test
